# Configuration for Rasa NLU.
# The language and pipeline keys specify the components used by the model to make NLU predictions. 
# The policies key defines the policies used by the model to predict the next action.
# https://rasa.com/docs/rasa/nlu/components/
language: zh

pipeline:
# # No configuration for the NLU pipeline was provided. The following default pipeline was used to train your model.
# # If you'd like to customize it, uncomment and adjust the pipeline.
# # See https://rasa.com/docs/rasa/tuning-your-model for more information.
  # - name: HFTransformersNLP
  #   model_name: bert
  #   model_weights: pretrained_model/bert-base-chinese
  #   cache_dir: null
  # - name: rasa_chinese.nlu.tokenizers.lm_tokenizer.LanguageModelTokenizer
  #   tokenizer_url: 'http://127.0.0.1:8000/'
  # - name: LanguageModelFeaturizer
  # - name: SklearnIntentClassifier
  # - name: CRFEntityExtractor

  - name: JiebaTokenizer
  - name: LanguageModelFeaturizer
    model_name: "bert"
    model_weights: "bert-base-chinese"
    cache_dir: ./cached
  - name: DIETClassifier                      # 意图分类和实体提取的双向转换器
    epochs: 100
  - name: EntitySynonymMapper
  - name: ResponseSelector
    epochs: 50

# Configuration for Rasa Core.
# https://rasa.com/docs/rasa/core/policies/
policies:
# # No configuration for policies was provided. The following default policies were used to train your model.
# # If you'd like to customize them, uncomment and adjust the policies.
# # See https://rasa.com/docs/rasa/policies for more information.
  - name: MemoizationPolicy
    max_history: 3  # 几轮对话
  - name: TEDPolicy
    max_history: 5
    epochs: 100
    constrain_similarities: true
    model_confidence: cosine
  - name: RulePolicy